services:
  # db:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_USER: ${DB_USER:-neondb_owner}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-npg_lSfE57AXNTLK}
  #     POSTGRES_DB: ${DB_NAME:-inventory_db}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      PORT: 3000
      DB_HOST: ep-raspy-lake-ah7olmg9.c-3.us-east-1.aws.neon.tech
      DB_PORT: 5432
      DB_USER: ${DB_USER:-neondb_owner}
      DB_PASSWORD: ${DB_PASSWORD:-npg_lSfE57AXNTLK}
      DB_NAME: ${DB_NAME:-inventory_db}
      DB_SSL: 'true'
    # depends_on:
    #   - db
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  db_data:
